config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :users do
      resources :photos
    end

    
    

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessor :reiviw
	belongs_to :user
	belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :photos, :dependent => :destroy
	has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def show
		@photo = Photo.find(params[:id])
		@comments = @photo.comments
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@photos = @user.photos
		
	end
		
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotosSharing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Individual Photo</title>
	
	
	
</head>
<body>
	<div class ="Photo"><%= image_tag(@photo.file_name) %></div>
	<% @comments.each do |comment| %>

			<div class = "comment_time"><p><%= comment.created_at %></p></div>
			<div class = "comment_name"><p>written by <%= "#{comment.user.first_name}, #{comment.user.last_name}" %></p></div>
			<div class = "comment_content"><%= comment.comment %></div>
	<% end %>
</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>PhotosSharing Website</title>
	<h1 class = "title"> All Users who share the photos</h1>
</head>
<body>
	<% @users.each do |user| %>
	<div class="user_id"><h3><%= user.id %></h3></div>
	<div class = "firstname"><p><%= user.first_name %></p></div>
	<div class = "lastname"><p><%= user.last_name %></p></div>
	<div class = "link"><p><%= link_to "#{user.first_name},#{user.last_name}", user %></p></div>
	<% end %>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Individual Website</title>
	
	<div class = "title"><h1> User: <%= "#{@user.first_name}, #{@user.last_name}" %></h1></div>
	
</head>
<body>
	<% @photos.each do |photo| %>
		<div class ="Photo"><%= image_tag(photo.file_name) %></div>
		<div class = "datetime"><h3><%= photo.created_at %></h3></div>
		<div class = "filename"><h3><%= photo.file_name %></h3></div>
		<div class="link"><h3><%= link_to "See the Comments ", user_photo_path(@user,photo) %></h3></div>
	<% end %>
</body>
</html>